#!/usr/bin/env python

from __future__ import division

import math
import sys

import numpy

import roslib
roslib.load_manifest('imagenex_852')
import rospy
from sensor_msgs.msg import PointCloud2

from imagenex_852 import driver, pointclouds

class Node(object):
    def __init__(self):
        port_filename = rospy.get_param('~port_filename', '/dev/ttyUSB0')
        frame_id = rospy.get_param('~frame_id', '/sonar')
        
        d = driver.Device(port_filename)
        
        pub = rospy.Publisher('imagenex_852', PointCloud2)
        while not rospy.is_shutdown():
            rospy.sleep(.03) # no response without this wait. why is this necessary?
            
            d.send_switch_data_command(train_angle_degrees=0, sector_width_degrees=360, step_size_degrees=3)
            res = d.read_sonar_return_data()
            
            array = numpy.zeros(len(res['echo_data']), dtype=[('x', numpy.float32), ('y', numpy.float32), ('z', numpy.float32), ('intensity', numpy.float32)])
            for i, x in enumerate(res['echo_data']):
                array[i]['x'] = res['range_meters'] * i/len(res['echo_data']) * math.cos(math.radians(res['head_position_degrees']))
                array[i]['y'] = res['range_meters'] * i/len(res['echo_data']) * math.sin(math.radians(res['head_position_degrees']))
                array[i]['z'] = 0
                array[i]['intensity'] = x/255
            
            pub.publish(pointclouds.array_to_pointcloud2(array, stamp=rospy.Time.now(), frame_id=frame_id))

if __name__ == '__main__':
    rospy.init_node('imagenex_852')
    try:
        n = Node()
    except rospy.ROSInterruptException:
        pass
