#!/usr/bin/env python

import roslib; roslib.load_manifest('uf_smach')
from uf_smach.states import WaypointState, OpenLoopState
from uf_smach.util import StateSharedHandles

import rospy
import smach
import smach_ros

def main():
    rospy.init_node('barrel_roll_state_machine')

    # Create a SMACH state machine
    sm = smach.Sequence(['succeeded'], 'succeeded')

    # Create all the stuff shared between states
    shared = StateSharedHandles()

    # Open the container
    with sm:
        # Add states to the container
        smach.Sequence.add('DEPTH', WaypointState(shared, lambda cur: cur.depth(1.5)))
        smach.Sequence.add('ROLL', OpenLoopState(shared, [80, 0, 0], 6.5))

    sis = smach_ros.IntrospectionServer('barrel_roll', sm, '/SM_ROOT')
    sis.start()

    # Execute SMACH plan
    outcome = sm.execute()

    rospy.spin()
    sis.stop()

if __name__ == '__main__':
    main()
