#!/usr/bin/env python

import sys

import roslib
roslib.load_manifest('kill_handling')
import rospy

from kill_handling.broadcaster import KillBroadcaster


rospy.init_node('kill', anonymous=True)

kill_br = KillBroadcaster(id=rospy.get_name(), lifetime=rospy.Duration(5), description='Command-line kill')

while not rospy.is_shutdown():
    kill_br.send(True)
    rospy.sleep(rospy.Duration(0.1))
