#!/usr/bin/python

import sys

from twisted.internet import defer, reactor

import txros


def parse_arg(arg):
    x = arg.split(',')
    return x[0], x[1:]

@defer.inlineCallbacks
def main():
    nh = txros.NodeHandle.from_argv('run_missions')
    
    missions = [(name, __import__(name, fromlist=['main']).main, args)
        for name, args in map(parse_arg, sys.argv[1:])]
    
    try:
        for name, func, args in missions:
            print
            print 'Starting', name
            yield func(nh, *args)
            print 'Finished', name
            print
    finally:
        import sub_scripting
        sub = yield sub_scripting.get_sub(nh)
        yield sub.move.go()


def run():
    def stopper(result):
        reactor.stop()
        return result
    main().addBoth(stopper)
reactor.callWhenRunning(run)
reactor.run()
