#!/usr/bin/python

import sys

from twisted.internet import defer, reactor

import txros


@defer.inlineCallbacks
def main():
    nh = txros.NodeHandle.from_argv('run_missions')
    
    missions = [(arg, __import__(arg, fromlist=['main']).main) for arg in sys.argv[1:]]
    
    try:
        for name, func in missions:
            print
            print 'Starting', name
            yield func(nh)
            print 'Finished', name
            print
    finally:
        import sub_scripting
        sub = yield sub_scripting.get_sub(nh)
        yield sub.move.go()


def run():
    def stopper(result):
        reactor.stop()
        return result
    main().addBoth(stopper)
reactor.callWhenRunning(run)
reactor.run()
