#!/usr/bin/env python

import os
import numpy
import threading
import math

import roslib
roslib.load_manifest('hydrophones')
import rospy

from hydrophones import algorithms
from hydrophones.msg import Ping, ProcessedPing, Debug
from std_msgs.msg import Header
from geometry_msgs.msg import Point, PoseStamped, Pose
import tf
from tf import transformations

def process_ping(ping):
    samples = numpy.array(ping.data, dtype=numpy.float64).reshape((ping.samples, ping.channels)).transpose()
    sample_rate = ping.sample_rate

    freq, valid = algorithms.check_data(samples, sample_rate)
 
    samples_proc, sample_rate_proc = algorithms.preprocess(samples, sample_rate)
    deltas = algorithms.compute_deltas(samples_proc, sample_rate_proc, 25e3, template_periods)
    pos = algorithms.compute_pos_4hyd(deltas, sample_rate_proc, v_sound, dist_h, dist_h4)

    _, quat = tf_listener.lookupTransform(output_frame, ping.header.frame_id, ping.header.stamp)
    pos_output = transformations.quaternion_matrix(quat)[:3, :3].dot(pos)
    heading = math.atan2(pos_output[1], pos_output[0])
    declination = math.asin(-pos_output[2])
    
    pub.publish(header=Header(stamp=ping.header.stamp,
                              frame_id=output_frame),
                heading=heading,
                declination=declination,
                freq=freq,
                valid=valid)
    pub_pose.publish(header=Header(stamp=ping.header.stamp,
                                   frame_id=ping.header.frame_id),
    pose=Pose(position=Point(*pos.tolist())))
    pub_debug.publish(header=Header(stamp=ping.header.stamp,
                                    frame_id=ping.header.frame_id),
                      deltas=deltas.tolist())

rospy.init_node('hydrophones')
dist_h = rospy.get_param('~dist_h')
dist_h4 = rospy.get_param('~dist_h4')
v_sound = rospy.get_param('~v_sound')
template_periods = rospy.get_param('~template_periods', 3)
output_frame = rospy.get_param('~output_frame', '/base_link')
tf_listener = tf.TransformListener()
pub = rospy.Publisher('hydrophones/processed', ProcessedPing)
pub_pose = rospy.Publisher('hydrophones/pose', PoseStamped)
pub_debug = rospy.Publisher('hydrophones/debug', Debug)
sub = rospy.Subscriber('hydrophones/ping', Ping, process_ping)
rospy.spin()
