#!/usr/bin/env python

from __future__ import division

import numpy

import roslib
roslib.load_manifest('thruster_mapper')
import rospy
from geometry_msgs.msg import WrenchStamped, Wrench, Vector3
from sensor_msgs.msg import Joy
from std_msgs.msg import Header


rospy.init_node('joy_to_wrench')

pub = rospy.Publisher('/wrench', WrenchStamped)
def cb(msg):
    pub.publish(WrenchStamped(
        header=Header(
            stamp=msg.header.stamp,
            frame_id='/base_link',
        ),
        wrench=Wrench(
            force=Vector3(
                x=msg.axes[1]*100,
                y=msg.axes[0]*100,
                z=msg.axes[3]*100,
            ),
            torque=Vector3(
                x=-msg.axes[4]*50,
                y=-msg.axes[5]*50,
                z=msg.axes[2]*50,
            ),
        ),
    ))
rospy.Subscriber('joy', Joy, cb)

rospy.spin()
